name=AtanStack
version=0.2.0
author=hrzhkm
maintainer=hrzhkm
sentence=AtanStack is an IoT data platform for connecting devices to real-time dashboards.
paragraph=Seamlessly connect your IoT devices into real-time dashboards with a simple begin()+send() client compatible with AtanStack ingestion.
category=Communication
url=https://github.com/hrzhkm/atanstack-arduino-lib
architectures=esp32,esp8266
depends=PubSubClient,ArduinoJson,ArduinoHttpClient
